services:
  - type: web
    name: pet-travel
    runtime: image
    plan: free
    buildCommand: ant dist
    startCommand: java -jar webapp-runner.jar --port $PORT dist/PetTravelDocs.war
    envVars:
      - key: RENDER
        value: true
      - key: JAVA_VERSION
        value: 17